type Patient {
    nhi: String!
    name: String!
}

type Medication {
    id: ID!
    dosage: String!
}

type Fhir {
    patient: Patient
    date: String!
    medications: [Medication]
}

type Query {
  patient(id: ID!): Fhir
  fhir: [Fhir]
  # Add other FHIR resource queries here
}

type Mutation {
    createFhir(nhi: String!, fhir: Fhir): Fhir
    updateFhir(nhi: String!, fhir: Fhir): Fhir
    deleteFhir(nhi: String!): Fhir
}